// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr0miH065RjqGBLelU7j8xOr8tt6fd9aY',
    appId: '1:686395484165:web:a5ddde63685d07247c146c',
    messagingSenderId: '686395484165',
    projectId: 'tallerines-verdes',
    authDomain: 'tallerines-verdes.firebaseapp.com',
    storageBucket: 'tallerines-verdes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXOqCGj1g_ehQYqPyJfK_s-92TeeTirYo',
    appId: '1:686395484165:android:4ff8dbe3e23da2027c146c',
    messagingSenderId: '686395484165',
    projectId: 'tallerines-verdes',
    storageBucket: 'tallerines-verdes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6TWSbditRlwSn7AfwT5AlnXJfksh9MVc',
    appId: '1:686395484165:ios:bec063b4ce12d7b17c146c',
    messagingSenderId: '686395484165',
    projectId: 'tallerines-verdes',
    storageBucket: 'tallerines-verdes.firebasestorage.app',
    iosBundleId: 'com.tallarinesverdes.tallarinesVerdesFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6TWSbditRlwSn7AfwT5AlnXJfksh9MVc',
    appId: '1:686395484165:ios:bec063b4ce12d7b17c146c',
    messagingSenderId: '686395484165',
    projectId: 'tallerines-verdes',
    storageBucket: 'tallerines-verdes.firebasestorage.app',
    iosBundleId: 'com.tallarinesverdes.tallarinesVerdesFlutter',
  );
}
